### ISSUE TITLE
Upgrade to Oxygen

### ISSUE THREAD

**Issue by dupuisa** [dupuisa/i-CodeCNES#54]

**Comment by opcoach** [comment]
This issue should be fixed by doing these changes in the fr.cnes.icode.tp.tpd file : 

- update the neon release location with oxygen
- update the delta pack location with 4.7 instead of 4.6
- update the orbit repository with the oxygen p2 repository : http://download.eclipse.org/tools/orbit/R-builds/R20170516192513/repository   (this can be found on this page : http://download.eclipse.org/tools/orbit/downloads/)

Then regenerate the '.target' file using the popup in the tpd editor. 

May be other changes regarding mocking or hamcrest should be done...
